### ISSUE TITLE
My autoresume doesn't completely work.

### ISSUE THREAD

**Issue by Yanishamburger** [Magmastream-NPM/magmastream#228]
Good evening, I have a question regarding auto resume, I activated it and when I turn off my application the music plays for 1 min if I do not turn the application back on, but if I turn the application back on directly after it does not recover not the old session with the music included in it while the lavalink server works well as it should, I don't see where the problem comes from could you enlighten me if it doesn't bother you, thank you in advance good evening.

Sincerely

![image](https://github.com/Blackfort-Hosting/magmastream/assets/121449519/c569f973-c7ab-444c-84c6-e18da00a7680)

**Comment by SxMAbel** [comment]
Not sure what is does yet, Auto resume is Lavalink feature not a feature that was built special for only magmastream

**Comment by Yanishamburger** [comment]
Hello, automatic recovery is not included in your magmastream module?

**Comment by SxMAbel** [comment]
> Hello, automatic recovery is not included in your magmastream module?

Currently being worked on
